### ISSUE TITLE
Request landmarkDetector.dat model

### ISSUE THREAD

**Issue by kairess** [vlachynska/Doggie-smile#2]
I saw your project and it is really nice!

I want to test your code but "landmarkDetector.dat" file is missing in your project.

Can you upload "landmarkDetector.dat" file?

Thanks!

**Comment by tureckova** [comment]
Hi,
thank you for your interest.
It is a rather big file, so it cannot be uploaded on Github. But you can download it from here:
https://owncloud.cesnet.cz/index.php/s/sc9kPUlOkYYvzxU
**ENJOY**
